import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { currentUser } from "@/helpers/current-user";
import Modals from "@/modals";
import Providers from "@/providers";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Toust",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await currentUser();

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} relative overflow-x-hidden antialiased`}
            >
                <Providers session={session}>
                    <main className="h-full w-full">{children}</main>
                    <Modals />
                </Providers>
            </body>
        </html>
    );
}
