import type { Metadata } from "next";
import { DM_Sans, Fredoka } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";
import { Modals } from "@/modals";
import { Providers } from "@/providers";

// TODO: Setup SEO
export const metadata: Metadata = {
    title: "Toust",
    description: "Generated by create next app",
};

export const dmSans = DM_Sans({
    display: "swap",
    subsets: ["latin"],
    variable: "--font-dmSans",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const fredoka = Fredoka({
    display: "swap",
    subsets: ["latin"],
    variable: "--font-fredoka",
    weight: ["300", "400", "500", "600", "700"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "overflow-x-hidden font-dmSans antialiased",
                    dmSans.variable,
                    fredoka.variable,
                )}
            >
                <Providers>
                    {children}
                    <Modals />
                </Providers>
            </body>
        </html>
    );
}
